# Generated by Django 5.1.4 on 2024-12-20 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courselike_created_at_coursepurchase_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='courselike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='coursepurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='ShippingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=150, verbose_name='Номер сертификата')),
                ('certificate_image', models.FileField(upload_to='uploads/certificates/', verbose_name='Изображение сертификата')),
                ('city', models.CharField(choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('shymkent', 'Шымкент'), ('karaganda', 'Караганда'), ('aktobe', 'Актобе'), ('pavlodar', 'Павлодар'), ('semey', 'Семей'), ('atyrau', 'Атырау'), ('uralsk', 'Уральск'), ('kostanay', 'Костанай'), ('kokshetau', 'Кокшетау'), ('taraz', 'Тараз'), ('kyzylorda', 'Кызылорда'), ('aktau', 'Актау')], max_length=150, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['id'],
            },
        ),
    ]
